include:
  - "iphone.glb"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
defaults:
  - scope:
      path: ""
      type: "glb"
    values:
      content_type: "model/gltf-binary"
